[package]
name = "spam-statistics"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
email = "0.0.21"
lettre = "0.11.15"
mime = "0.3.17"
regex = "1.11.1"
thiserror = "2.0.12"
